### ISSUE TITLE
Disable infinite map tiling

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#124]
**Describe the bug**
The map tiles infinitely. It serves no discernible purpose, and can be confusing. 

**To Reproduce**
Drag the map farther than you usually would, and see that it will keep going on forever.

**Expected behavior**
There should only have one projection of the map.

**Screenshots**
![tiling](https://user-images.githubusercontent.com/5544782/50252943-37221f80-03c3-11e9-9bc3-01a43c9b7afb.png)

**Comment by jackharrhy** [comment]
The leafletjs docs mention this option:

> worldCopyJump | Boolean | false | With this option enabled, the map tracks when you pan to another "copy" of the world and seamlessly jumps to the original one so that all overlays like markers and vector layers are still visible.

By default it is false.

However, this might be a feature of a newer version of leaflet, since this option does not seem to exist in our codebase and we have leaflet installed locally.

But we also have leaflet installed through npm, so maybe we can remove it locally and use that instead and let npm take care of updating it for us?

**Comment by jackharrhy** [comment]
https://github.com/Leaflet/Leaflet/issues/105

> I figured it out.. it's not documented! There is a L.TileLayer option called noWrap; set that to true and wrapping disappears!

**Comment by ecumene** [comment]
Fixerupped in da #165
