### ISSUE TITLE
Incorrect colour coding on certain subsidy sub-layers

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#129]
**To Reproduce**
1. Open the Choropleth layer
2. Click on 'Subsidies x 1000 000 USD'
3. Hover over a country, in this particular case, Greenland
4. See that even though Greenland has 'No data', it is shaded in with the colour for "0"

**Expected behavior**
All country colours should match appropriately to their values and to the map key/legend.

**Comment by ecumene** [comment]
`{ "type": "Feature", "properties": { "name": "Côte d'Ivoire", "Copy of Country_Statistics_ma New Launch_SSF_1": null, "Copy of Country_Statistics_ma New Launch_SSF_2": null, "Copy of Country_Statistics_ma New Launch_SSF_3": null, "Copy of Country_Statistics_ma New Launch_SSF_4": null, "Copy of Country_Statistics_ma New Launch_SSF_5": null, "Copy of Country_Statistics_ma New Launch_SSF_6": null, "Copy of Country_Statistics_ma New Launch_SSF_7": null, "Copy of Country_Statistics_ma New Launch_SSF_8": null, "Copy of Country_Statistics_ma New Launch_SSF_9": null, "Copy of Country_Statistics_ma New Launch_SSF_10": null, "Copy of Country_Statistics_ma New Launch_SSF_11": null, "Copy of Country_Statistics_ma New Launch_SSF_12": null, "Copy of Country_Statistics_ma New Launch_SSF_13": null, "Copy of Country_Statistics_ma New Launch_SSF_14": null, "Copy of Country_Statistics_ma New Launch_SSF_15": null }`

This issue is almost resolved on my private branch. Except some of the data causes deeper errors, which I can't debug right now. The table above is for a small African country with an empty database. This breaks the Choropleth Legend so it still reports "0", even when the color is grayed out.

**Comment by ecumene** [comment]
Fixed in dat #165
