### ISSUE TITLE
Certain profiles do not show the correct date range on their profile page (or in the generated report)

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#15]
**Describe the bug**
Profiles do not always show the correct date range. Sometimes only the first year will come up, i.e 2015 instead of 2015-2016. This also occurs when a PDF report is generated of that record.

**To Reproduce**
1. Open an SSF Profile record that you know has a date range.
2. Generate a PDF report and see that is also has the issue.

**Expected behavior**
Should have a year-year format like 1998-2002

**Comment by nint8835** [comment]
Manually reviewed database, and all rows in database that have a start and end row show the start and end row on the page. However, there are multiple rows with duplicate names and only the one with the most recent ISSF Core ID is displayed. In many cases, the duplicates that are not displayed contain end years, but the one that is shown doesn't contain said row.

For example:
- Lake Mutirikwi (ISSF Core ID 3586): https://issfcloud.toobigtoignore.net/details/profile/3586
- Lake Mutirikwi (ISSF Core ID 3587): https://issfcloud.toobigtoignore.net/details/profile/3587
- **Lake Mutirikwi (ISSF Core ID 3588): https://issfcloud.toobigtoignore.net/details/profile/3588**

In the database, 3586 and 3587 both have end years, but 3588 does not. Since they have duplicate names, 3588 is displayed due to having the highest ISSF Core ID, and since it has no end year, no end year is displayed on the report.

**Comment by nint8835** [comment]
Just created a ssf profile, and there was no end year displayed even though I entered one. As far as I can tell, the data is being dropped before it hits the database, as the entry in the database was also missing the end year.
