### ISSUE TITLE
Records with no geographic scope of "Not specific"show up on the map in the middle of the ocean

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#2]
As seen in the picture below, records that have a geographic scope of "Not specific" show up in the middle of the ocean.

Currently open to suggestions as to how this should be resolved (i.e should these records be hidden on the map altogether, only showing up in the table?)

![points](https://user-images.githubusercontent.com/5544782/50172309-5770b200-02cf-11e9-97f5-fff86db6bdfc.png)

**Comment by nint8835** [comment]
I'd say the best option would be to not display them on the map at all, because it's a bit hard to find a place on a map to put something that has no location.

**Comment by jackharrhy** [comment]
The UI doesn't even render them properly since they are all clumped up together, therefore I also vote we remove them from the map.

I believe we also have a few residences of [`null`  island](https://en.wikipedia.org/wiki/Null_Island).

![50172309-5770b200-02cf-11e9-97f5-fff86db6bdfc_png__1083x737_](https://user-images.githubusercontent.com/6486417/50172993-e03c1d80-02d0-11e9-9782-ad1742626769.png)

**Comment by ecumene** [comment]
Perhaps a line under the map saying **"x SSFs not shown"**?
