### ISSUE TITLE
Upgrade to HTTP/2

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#39]
Upgrading to HTTP/2 would likely bring a large performance boost. A small portion of unsupported browsers would revert back to HTTP1.1 and would be able to continue using the ISSF unaffected.

**Comment by ecumene** [comment]
After some deep digging and experimentation, the only practical solution to this would be to use Nginx server push (in 1.13) to fully utilize the power of HTTP2. There is a docker+django+nginx repository here with a full implementation (also using uwsgi).

https://github.com/DistPub/nginx-http2-django-server-push

I am adding a not fixing label to this, only because adding this server push feature would be a very big change in frontend code, changing every line an asset is mentioned to be flagged as pushable by the middleware. We should implement HTTP2 and Server Push at the same time, because they follow this example repositories format, minimizing possible errors we could make.
